### ISSUE TITLE
refresh tables button keeps loading and loading

### ISSUE THREAD

**Issue by m-kroener** [acebusters/ab-web#814] opened 2017-11-26 14:32 UTC
Left table after standup, then the button was loading and loading and the table still shows 2/2, but both players stood up. 

<img width="778" alt="bildschirmfoto 2017-11-26 um 15 31 17" src="https://user-images.githubusercontent.com/31517309/33240931-0834e58a-d2bf-11e7-92ca-ab4f1ae6eda0.png">

**Comment by sunify** [comment] 2017-12-04 15:57
Related to 808

**Comment by sunify** [comment] 2017-12-22 07:13
Not able to reproduce anymore. Possibly fixed with #835

**Closed by sunify** 2017-12-22 07:13 UTC
