### ISSUE TITLE
players see zero balance after rebuy until he refreshes the page

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#699] opened 2017-09-26 12:50 UTC
Sandbox v1.0.0_1505822706752

**Comment by sunify** [comment] 2017-10-31 14:06
Probably will be fixed with https://github.com/acebusters/oracle-cashgame/pull/47

**Comment by troggy** [comment] 2017-11-17 09:22
still relevant for 1.5.0

**Comment by troggy** [comment] 2017-11-17 09:22
happened on 6max table with 3 players

**Comment by mateleshkavo** [comment] 2017-12-20 14:29
I guess this one was fixed in the latest fix for v1.6, @sunify can you please confirm?

**Comment by sunify** [comment] 2017-12-21 04:05
Nope, it still reproduces. Sometimes the player doesn't receive `Join` event on table contract and doesn't update the balance. Will try to fix it today

**Comment by sunify** [comment] 2018-01-16 04:50
Not sure we are able to do smth about that. Looks like websocket skips frame sometimes

**Closed by sunify** 2018-01-16 04:50 UTC
Labels: bug
