### ISSUE TITLE
was asked to rebuy right after I sat at the table

### ISSUE THREAD

**Issue by troggy** [acebusters/ab-web#681] opened 2017-09-22 14:45 UTC
Production
Table https://dapp.acebusters.com/table/0x81b94ee5dbe3c45aab492069928af651a83d052e
Hand 69

One guy was in sit out at the table. I joined with 200 NTZ stack and immediatelly was asked either to rebuy or leave

**Comment by grabus** [comment] 2017-09-24 15:14
tried a lot of scenarios, can't reproduce it.

**Comment by sunify** [comment] 2017-09-25 05:06
Caught the same bug on production. I think there is some time gap when you have a zero balance after joining. Need to check the condition of Rebuy dialog showing

**Comment by troggy** [comment] 2017-10-09 09:10
just experienced this on production. Probable clue: join transaction was really slow to mine and at some point my seat at the table become empty. Once tx was mined, I appear at the table but was asked for rebuy

**Comment by sunify** [comment] 2017-10-31 14:10
If it so, it should be fixed now. We don't release seat before tx result anymore.

Also, there were problems with lineup update after contract events (Join, Leave, etc). It could be the reason. Fixed here https://github.com/acebusters/oracle-cashgame/pull/47

**Closed** 2017-12-11 04:42 UTC
Labels: bug
